services:
  postgres:
    image: postgres:16-alpine
    container_name: school-ms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school_ms
    ports:
      - "5432:5432"
    volumes:
      - school_ms_postgres:/var/lib/postgresql/data

volumes:
  school_ms_postgres:
