ALTER TABLE "Vehicle" ADD COLUMN "latitude" DOUBLE PRECISION;
ALTER TABLE "Vehicle" ADD COLUMN "longitude" DOUBLE PRECISION;
ALTER TABLE "Vehicle" ADD COLUMN "heading" DOUBLE PRECISION;
ALTER TABLE "Vehicle" ADD COLUMN "speed" DOUBLE PRECISION;
ALTER TABLE "Vehicle" ADD COLUMN "locationUpdatedAt" TIMESTAMP(3);
